apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-secret
  namespace: production
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: stripe-secret
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_KEY
      remoteRef:
        key: secret/myesi/stripe
        property: STRIPE_KEY
