apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: production
spec:
  provider:
    vault:
      server: "http://vault.production.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          role: "eso-role"
          serviceAccountRef:
            name: external-secrets-sa
            namespace: production
